export const RAW_KEYS = {
  'civilite': 'civilite',
  'nom': 'nom',
  'prenom': 'prenom',
  'telephone portable': 'telephone',
  'telephone': 'telephone',
  'telephone domicile': 'telephone_domicile',
  'email': 'email',
  'code postal': 'codePostal',
  'codepostal': 'codePostal',
  'ville': 'ville',
  'date de naissance': 'dob',
  'age': 'age',
  'sexe': 'sexe',
  'besoin assurance sante': 'besoin',
  'mois d\'echeance': 'mois_echeance',
  'mois d echeance': 'mois_echeance',
  'regime social': 'regime_social',
  'situation familiale': 'situation_familiale',
  'profession': 'profession',
  'nombre d\'enfants': 'nb_enfants',
  'date de naissance enfants min': 'dob_enfant_min',
  'date de naissance enfants max': 'dob_enfant_max',
  'date de naissance conjoint': 'dob_conjoint',
  'date de naissance du 1er enfant': 'dob_enfant_1',
  'date de naissance du 2eme enfant': 'dob_enfant_2',
  'date de naissance du 3eme enfant': 'dob_enfant_3',
  'regime social conjoint': 'regime_social_conjoint',
  'profession conjoint': 'profession_conjoint',
  'assureur actuel': 'assureur_actuel',
  'formule choisie': 'formule',
  'user_id': 'user_id',
  'user id': 'user_id',
  'userid': 'user_id',
  'v2': 'complement_adresse',
  'v4': 'adresse',
  'adresse': 'adresse',
  // Nouveaux mappings basés sur email_text_vrac.txt
  'travailleurs non salaries': 'regime_social',
  'profession liberale': 'profession',
  'ticket moderateur': 'formule',
  'intermediaire': 'formule',
  'vous assurer pour la premiere fois': 'besoin',
  'changer de contrat': 'besoin',
  'celibataire': 'situation_familiale',
  'divorce': 'situation_familiale',
  'axa courtage': 'assureur_actuel'
};